### PR TITLE
Notebook for training for the configured data.

### PR DESCRIPTION
**Pull request by nvk681**

### CODE REVIEW

**Comment by nvk681** [comment]
@Mrinal18  I will make few more changes, for this to work with video. Will create a new Pr on this. These will the current changes for this PR. Will send a new PR for the rest of the changes.

**Comment by Mrinal18** [comment]
if you create a new PR, does that mean this notebook will not be relevant then? because you can push all the changes in this PR as well and it wont make a difference

**Comment by nvk681** [comment]
It will be changed on this notebook, so the new changes will be easy to refer to. This notebook will be my point of change

**Review by gsvsumanth — APPROVED** [review]

**Comment by Mrinal18** [comment]
Merging this PR since everyone approved it! good job guys!! :D

**Pull request merged**
